Unity 3.4.2 Adapter Update
Applifier/googleads-mobile-android-mediation pull request #3
Opened 2020-01-23 21:54 UTC by jindoujiao

Update Admob Unity Adapter.

2020-01-24 20:58 UTC, thatguyhampton requested changes

2020-01-24 20:58 UTC, thatguyhampton commented on ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnityAdapter.java
> +            //todo: no fill
Can probably remove this comment

2020-01-24 20:58 UTC, thatguyhampton commented on ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnityAdapter.java
> +        return null;
Should this be returning `mBannerView`?

2020-01-31 19:11 UTC, serge-14 commented on ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnityAdapter.java
> +                        mMediationInterstitialListener.onAdFailedToLoad(UnityAdapter.this, AdRequest.ERROR_CODE_INTERNAL_ERROR);
according to docs, `mMediationInterstitialListener.onAdFailedToLoad` should be used only when we failed to load ad.

2020-01-31 19:11 UTC, serge-14 commented on ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnityAdapter.java
> +                        mMediationInterstitialListener.onAdFailedToLoad(UnityAdapter.this, AdRequest.ERROR_CODE_INTERNAL_ERROR);
It looks like we should just ignore error here and do nothing. Also we should check with AdMob team.

2020-01-31 19:11 UTC, serge-14 commented on ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnityAdapter.java
> +                        UnityAds.load(mPlacementId);
why can't we call load right after init?

```
UnitySingleton.getInstance().initializeUnityAds(...);
UnityAds.load(mPlacementId);
```

2020-01-31 19:11 UTC, serge-14 commented on ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnityAdapter.java
> +            mMediationInterstitialListener.onAdFailedToLoad(UnityAdapter.this, AdRequest.ERROR_CODE_INVALID_REQUEST);
Same comment as above for `mMediationInterstitialListener.onAdFailedToLoad`

2020-01-31 19:11 UTC, serge-14 commented on ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnityMediationAdapter.java
> +    private int impressionOrdinal;
looks like we are not using those.

2020-01-31 19:11 UTC, serge-14 commented on ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnitySingleton.java
> -    private HashMap<String, WeakReference<UnityAdapterDelegate>> mPlacementsInUse;
why do we remove it?

2020-02-20 05:25 UTC, serge-14 commented on ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnityAdapter.java
> +                        UnitySingleton.getInstance().mPlacementsInUse.add(mPlacementId);
should we set it before calling `initializeUnityAds`? also if it is in we should report no fill immideatly to be aligned with previous implementation.

2020-02-20 05:27 UTC, serge-14 commented on ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnityAdapter.java
> +        MetaData metadata = new MetaData((mActivityWeakReference.get()));
should we remove placement id from  `UnitySingleton.getInstance().mPlacementsInUse`?

2020-02-20 05:29 UTC, serge-14 commented on ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnityMediationAdapter.java
> +        if (UnitySingleton.getInstance().mPlacementsInUse.contains(placementId)) {
this is will report invalid request error... old implementation had no fill.

2020-09-25 16:35 UTC, merged